### ISSUE TITLE
Forum Coding (Preparations)

### ISSUE THREAD

**Issue by RenrenYGO** [RenrenYGO/Team-06-BSCS3CD#13]
starting the preparations / laying the foundations of coding Commhub

**Comment by Xvareon** [comment]
Started 11-25-21.

**Comment by T0RIEL** [comment]
Starting threads

**Comment by RenrenYGO** [comment]
backend team is currently on the case!

**Comment by Xvareon** [comment]
Started threads database.

**Comment by RenrenYGO** [comment]
Part 1 of preparations done, will continue in later weeks.

**Comment by T0RIEL** [comment]
Closing the forum coding preparations
